// --- DATA (v6.2 - Hoàn thiện & Sửa lỗi) ---

/**
 * Dữ liệu về các bản cập nhật trong hệ sinh thái.
 * Được sắp xếp theo thứ tự ngày giảm dần.
 */
const updatesData = [
    {
        date: '2025-08-23',
        type: 'new_feature',
        title_key: 'update_search_feature_title',
        content_key: 'update_search_feature_content',
    },
    {
        date: '2025-08-19',
        type: 'new_bot',
        title_key: 'update_new_bot_kite_title',
        content_key: 'update_new_bot_kite_content',
    },
    {
        date: '2025-08-16',
        type: 'new_bot',
        title_key: 'update_new_bot_cpu_title',
        content_key: 'update_new_bot_cpu_content',
    },
    {
        date: '2025-08-06',
        type: 'new_feature',
        title_key: 'update_repo_readme_title',
        content_key: 'update_repo_readme_content',
    },
    { 
        date: '2025-08-05', 
        type: 'new_bot',
        title_key: 'update_new_bot_radish_title',
        content_key: 'update_new_bot_radish_content',
    },
    { 
        date: '2025-08-01', 
        type: 'bot_update',
        title_key: 'update_iminibot_391_title',
        content_key: 'update_iminibot_391_content',
    },
];

/**
 * Dữ liệu chi tiết về tất cả các bot trong hệ sinh thái.
 */
const botsData = [
    { id: 'iminibot', name: 'IminiBot', isMain: true, tech: { lang: 'Python', lib: 'Nextcord', db: 'PostgreSQL', host: 'VoidNodes' }, config: { ram: 16 * 1024, cpu: '1500%', disk: '20GB' }, status: { version: 'v3.9.1', key: 'stable' }, translation_keys: { role: 'role_iminibot', history: 'history_iminibot', roadmap: 'roadmap_iminibot' } },
    { id: 'ramteaser', name: 'RAM Teaser', tech: { lang: 'JavaScript', lib: 'discord.js', host: 'Bot-hosting' }, config: { ram: 1024, cpu: '50%', disk: null }, status: { version: 'v1.0', key: 'stable' }, translation_keys: { role: 'role_ramteaser', history: 'history_ramteaser', funFact: 'funFact_ramteaser' } },
    { id: 'teaserlite', name: 'Teaser Lite', tech: { lang: 'Python', lib: 'discord.py', host: 'Zluqe' }, config: { ram: 256, cpu: '50%', disk: null }, status: { version: 'v1.0', key: 'stable' }, translation_keys: { role: 'role_teaserlite', history: 'history_teaserlite', funFact: 'funFact_teaserlite' } },
    { id: 'teaserpotato', name: 'Teaser Potato', tech: { lang: 'JavaScript', lib: 'Eris', host: 'Lunes' }, config: { ram: 128, cpu: '15%', disk: null }, status: { version: 'v1.0', key: 'stable' }, translation_keys: { role: 'role_teaserpotato', history: 'history_teaserpotato', funFact: 'funFact_teaserpotato' } },
    { id: 'teaserhardcore', name: 'Teaser Hardcore', tech: { lang: 'Java', lib: 'Discord4J', host: 'Karlo' }, config: { ram: 150, cpu: '100%', disk: null }, status: { version: 'v1.0', key: 'stable' }, translation_keys: { role: 'role_teaserhardcore', history: 'history_teaserhardcore', funFact: 'funFact_teaserhardcore' } },
    { id: 'teaserdust', name: 'Teaser Dust', tech: { lang: 'JavaScript', lib: 'Raw WebSocket', host: 'Karlo' }, config: { ram: 50, cpu: '100%', disk: null }, status: { version: 'v1.0', key: 'stable' }, translation_keys: { role: 'role_teaserdust', history: 'history_teaserdust', funFact: 'funFact_teaserdust' } },
    { id: 'playercycle', name: 'Teaser Cycle', tech: { lang: 'Python', lib: 'Interactions.py', host: 'Fps.ms' }, config: { ram: 128, cpu: '25%', disk: null }, status: { version: 'v1.1', key: 'dev' }, translation_keys: { role: 'role_playercycle', history: 'history_playercycle', funFact: 'funFact_playercycle' } },
    { id: 'teasermusic', name: 'Teaser Music', tech: { lang: 'Java', lib: 'JDA (JMusicBot)', host: 'HMB' }, config: { ram: 2048, cpu: '200%', disk: '4GB' }, status: { version: 'v1.0', key: 'dev' }, translation_keys: { role: 'role_teasermusic', history: 'history_teasermusic', funFact: 'funFact_teasermusic' } },
    { id: 'teaserdrift', name: 'Teaser Drift', tech: { lang: 'Python', lib: 'Pycord', host: 'Daki' }, config: { ram: 512, cpu: '50%', disk: '1GB' }, status: { version: 'v1.0', key: 'dev' }, translation_keys: { role: 'role_teaserdrift', history: 'history_teaserdrift', funFact: 'funFact_teaserdrift' } },
    { id: 'teaserai', name: 'Teaser AI', tech: { lang: 'JavaScript', lib: 'discord.js', host: 'Hidencloud' }, config: { ram: 3 * 1024, cpu: '200%', disk: '15GB' }, status: { version: 'v1.0-beta', key: 'dev' }, translation_keys: { role: 'role_teaserai', history: 'history_teaserai', funFact: 'funFact_teaserai' } },
    { id: 'teaserultra', name: 'Teaser Ultra', tech: { lang: 'Rust', lib: 'Twilight', db: 'Supabase', host: 'HMB' }, config: { ram: 2048, cpu: '200%', disk: '3GB' }, status: { version: 'v0.0.2-alpha', key: 'dev' }, translation_keys: { role: 'role_teaserultra', history: 'history_teaserultra', funFact: 'funFact_teaserultra' } },
    { id: 'teaserradish', name: 'Teaser Radish', tech: { lang: 'JavaScript', lib: 'Oceanic.js', host: 'KataBump' }, config: { ram: 308, cpu: '25%', disk: '716MB' }, status: { version: 'v1.0-release', key: 'stable' }, translation_keys: { role: 'role_teaserradish', history: 'history_teaserradish', funFact: 'funFact_teaserradish' } },
    { id: 'cputeaser', name: 'CPU Teaser', tech: { lang: 'Python', lib: 'Disnake', db: 'SQLite', host: 'Orihost' }, config: { ram: 512, cpu: '100%', disk: '1GB' }, status: { version: 'v1.0', key: 'stable' }, translation_keys: { role: 'role_cputeaser', history: 'history_cputeaser', funFact: 'funFact_cputeaser' } },
    { id: 'teasereclipse', name: 'Teaser Eclipse', tech: { lang: 'Lua', lib: 'Concord', db: 'TeaserDB (MongoDB)', host: 'WispByte' }, config: { ram: 512, cpu: '100%', disk: '1GB' }, status: { version: '', key: 'planned' }, translation_keys: { role: 'role_teasereclipse', history: 'history_teasereclipse' } },
    { id: 'teaserrebun', name: 'Teaser Rebun', tech: { lang: 'Bun', lib: 'Bun + discord.js', db: 'Planning...', host: 'SillyDev' }, config: { ram: 2048, cpu: '100%', disk: '3GB' }, status: { version: '', key: 'planned' }, translation_keys: { role: 'role_teaserrebun', history: 'history_teaserrebun' } },
    { id: 'teaserkite', name: 'Teaser Kite', tech: { lang: 'Kite', lib: 'Kite', host: 'Kite' }, config: { ram: null, cpu: null, disk: null }, status: { version: 'Kite/10', key: 'joke' }, translation_keys: { role: 'role_teaserkite', history: 'history_teaserkite', funFact: 'funFact_teaserkite' } },
    { id: 'teaserscnx', name: 'Teaser SCNX', tech: { lang: 'SCNX', lib: 'SCNX', host: 'SCNX' }, config: { ram: null, cpu: null, disk: null }, status: { version: 'SCNX/10', key: 'joke' }, translation_keys: { role: 'role_teaserscnx', history: 'history_teaserscnx', funFact: 'funFact_teaserscnx' } }
];

/**
 * Đối tượng chứa tất cả các chuỗi dịch cho đa ngôn ngữ.
 */
const translations = {
    en: {
        main_title: "Teaserverse Ecosystem", main_subtitle: "An interactive analysis of the bot projects, their technologies, and the stories behind them.",
        tab_overview: "Overview", tab_updates: "Updates",
        ram_chart_title: "RAM Allocation (MB)", lang_chart_title: "Language Distribution",
        directory_title: "Bot Directory", filter_all: "All", filter_stable: "Stable", filter_dev: "In Development", filter_planned: "Planned", filter_joke: "Joke",
        view_details: "View Details", modal_role: "Role & Functionality", modal_history: "History & Context", modal_fun_fact: "Fun Fact", modal_roadmap: "Roadmap", modal_tech_specs: "Technical Specifications", modal_status: "Status", modal_host: "Host", modal_db: "Database",
        card_ram: "RAM", card_cpu: "CPU", card_disk: "Disk",
        update_type_bot_update: "Bot Update", update_type_new_feature: "New Feature", update_type_new_bot: "New Bot",
        update_iminibot_391_title: "IminiBot v3.9.1 - Stability Patch",
        update_iminibot_391_content: "Released a patch for IminiBot to address database connection issues and improve profile command performance.",
        update_repo_readme_title: "Transparency Initiative: Repos & READMEs Added",
        update_repo_readme_content: "Public repositories and detailed README.md files have been released for several bots. IminiBot's README.md has also been updated.",
        update_new_bot_radish_title: "Welcome Teaser Radish!",
        update_new_bot_radish_content: "A new bot, Teaser Radish, has joined the ecosystem. This French-speaking bot is built with Oceanic.js and is designed for maximum stability.",
        update_new_bot_cpu_title: "CPU Teaser has arrived!",
        update_new_bot_cpu_content: "The 'digital philosopher' CPU Teaser is now online. Built with Python and Disnake, it's ready to share its thoughts.",
        update_new_bot_kite_title: "Look, up in the sky! It's Teaser Kite!",
        update_new_bot_kite_content: "A new... entity... has appeared in the Teaserverse. Its purpose is as clear as its language: Kite!!",
        update_search_feature_title: "Search Bar Improvements",
        update_search_feature_content: "Added explicit search button, result highlighting across cards and modals, and a clear (✖) action next to search results for faster exploration.",
        dev_modal_title: "About the Developer", dev_modal_content: "A somewhat lazy dev, proficient in Python, Node.js, and currently learning Java. Enjoys programming a diverse range of bots with various languages.",
        chart_bot_singular: "bot", chart_bot_plural: "bots",
        timeline_link: "Timeline",
        settings_title: "Settings", language_settings_title: "Language Settings", theme_settings_title: "Theme Settings",
        role_iminibot: 'Provides a comprehensive entertainment ecosystem including economy, minigames, jobs, and profile customization. It exclusively uses prefix commands.', history_iminibot: 'Started from the no-code platform Botghost, then completely rewritten in Python. "IminiBot (test)" was a staging version until v3.2 before being retired. The "Great Update" phase (v3.3 - v3.8) saw rapid development, sometimes with two updates in one day.', roadmap_iminibot: 'Heading towards "Huge Update 4.0: The Changed of The Era".',
        role_ramteaser: 'The first Teaser bot. Monitors content from 2 YouTube channels and continuously changes its status.', history_ramteaser: 'Born from a failure to host IminiBot, it was the "ancestor" that sparked the Teaserverse. Initially used Nextcord, experimented with JDA (failed), and finally stabilized with discord.js.', funFact_ramteaser: 'Has the highest uptime in Teaserverse. As long as Bot-hosting is alive, its uptime will keep increasing.',
        role_teaserlite: 'Monitors and updates server stats every 5 minutes.', history_teaserlite: 'Originally named "Teaser Bun" (using Bun.js). Due to host issues, the project was "overwritten" and completely rewritten in discord.py.', funFact_teaserlite: 'Its configuration will never change due to the severe limitations of its host, Zluqe.',
        role_teaserpotato: 'Randomly changes status and provides a few basic slash commands.', history_teaserpotato: 'Born from the free resources of Lunes host. Uses the ultra-lightweight Eris library to optimize for extremely limited specs. Was once rate-limited by Discord due to excessive restarts during debugging.', funFact_teaserpotato: 'If lucky, it could be upgraded to "Teaser Potato Ultimate" for over 4 hours with specs powerful enough to "crush the entire Teaserverse." This will never happen.',
        role_teaserhardcore: 'Provides 5 niche slash commands, living up to its name by running the difficult Discord4J library.', history_teaserhardcore: 'An experiment in the developer\'s endurance against a complex library. It suffers from a slow memory leak.', funFact_teaserhardcore: 'Will not be updated due to the library\'s complexity. The host, Karlo, provides 3x more RAM for Java bots, which is how Hardcore exists.',
        role_teaserdust: 'Sends heartbeats and maintains a connection with the Discord API without any library, using only raw WebSockets.', history_teaserdust: 'Born from the idea "instead of complaining about 50MB RAM, why not optimize it as much as possible?". The entire bot is contained in a single file.', funFact_teaserdust: 'Lives like a speck of dust, needing no attention.',
        role_playercycle: 'Acts as the "historian" of Teaserverse, providing information about all bots, including the fallen ones.', history_playercycle: 'Frequently offline because the developer forgets to renew the host daily. It is currently "researching" the secret origin of Teaserverse.', funFact_playercycle: 'The avatar slideshow feature was added but no one cares if it actually works.',
        role_teasermusic: 'Music bot using a modified version of JMusicBot (JDA).', history_teasermusic: 'A "spinning top" development history. After many failed attempts at coding it from scratch due to forgetting to install ffmpeg, the project switched to the JMusicBot platform.', funFact_teasermusic: 'The developer spent about 15 hours over 3 sessions trying to fix Lavalink before realizing ffmpeg was missing.',
        role_teaserdrift: 'Manages an advanced Giveaway system with many features.', history_teaserdrift: 'Inherited the Giveaway feature originally intended for Teaser Ultra. Appeared randomly as a "rich kid" in the ecosystem.', funFact_teaserdrift: 'Will be updated with Quality of Life features.',
        role_teaserai: 'Integrates the Gemini API to provide AI features. Supports both Prefix and Slash commands.', history_teaserai: 'Initially developed in C# (Discord.Net). Due to limited host support, the project was refactored to Node.js to "trade coolness for performance".', funFact_teaserai: 'Expected to become the most powerful Teaser bot (besides IminiBot).',
        role_teaserultra: 'The most ambitious project, intended to have many complex features.', history_teaserultra: 'Delayed 4 times due to the creation of other Teaser bots. Currently only has /ping and /mood commands.', funFact_teaserultra: 'All 4 delays were caused by the developer getting distracted and creating other Teaser bots instead.',
        role_teaserradish: 'A French-speaking bot. Its role is to be stable and require minimal updates.', history_teaserradish: 'Planned for the KataBump host (a French host), using the Oceanic.js library. Everything about it is in French, from console logs to code comments.', funFact_teaserradish: 'This is the first Teaser bot with a properly written README.md.',
        role_cputeaser: 'A "digital philosopher" that provides thoughts and philosophical quotes.', history_cputeaser: 'Hosted temporarily on Orihost after a bad experience with EchoHost, which falsely advertised its CPU resources.', funFact_cputeaser: 'The developer was tricked by EchoHost\'s "80vCores CPU" promise, which turned out to be only 80% of a single core.',
        role_teasereclipse: 'A planned bot that will monitor player status and speak Russian.', history_teasereclipse: 'A project planned for the WispByte host to monitor player activity.',
        role_teaserrebun: 'A planned bot to provide temporary voice channels (TempVoice).', history_teaserrebun: 'The revenge of Teaser Bun. Planned to be reborn using modern Bun technology on SillyDev.',
        role_teaserkite: 'Kite!!', history_teaserkite: 'Kite!!', funFact_teaserkite: 'Kite!!',
        role_teaserscnx: 'SCNX', history_teaserscnx: 'SCNX', funFact_teaserscnx: 'This is an internal joke in Teaserverse.',
        
        // Search-related translations
        search_placeholder: 'Search bots...',
        search_no_results: 'No results found',
        search_no_results_desc: 'No bots matched "{term}"',
        search_results: 'Search results',
        search_result: 'result',
        search_results_plural: 'results',
    },
    vi: {
        main_title: "Hệ sinh thái Teaserverse", main_subtitle: "Một bản phân tích tương tác về các dự án bot, công nghệ và câu chuyện đằng sau chúng.",
        tab_overview: "Tổng quan", tab_updates: "Cập nhật",
        ram_chart_title: "Phân bổ RAM (MB)", lang_chart_title: "Phân bổ Ngôn ngữ",
        directory_title: "Danh bạ Bot", filter_all: "Tất cả", filter_stable: "Ổn định", filter_dev: "Phát triển", filter_planned: "Dự kiến", filter_joke: "Trò đùa",
        view_details: "Xem chi tiết", modal_role: "Vai trò & Chức năng", modal_history: "Lịch sử & Bối cảnh", modal_fun_fact: "Sự thật thú vị", modal_roadmap: "Lộ trình", modal_tech_specs: "Thông số Kỹ thuật", modal_status: "Tình trạng", modal_host: "Host", modal_db: "Database",
        card_ram: "RAM", card_cpu: "CPU", card_disk: "Disk",
        update_type_bot_update: "Cập nhật Bot", update_type_new_feature: "Tính năng mới", update_type_new_bot: "Bot mới",
        update_iminibot_391_title: "IminiBot v3.9.1 - Bản vá ổn định",
        update_iminibot_391_content: "Phát hành bản vá cho IminiBot để giải quyết các vấn đề kết nối cơ sở dữ liệu và cải thiện hiệu suất lệnh profile.",
        update_repo_readme_title: "Sáng kiến Minh bạch: Thêm Repo & README",
        update_repo_readme_content: "Các kho mã nguồn và file README.md chi tiết đã được công khai cho một số bot. IminiBot cũng đã được cập nhật README.md.",
        update_new_bot_radish_title: "Chào mừng Teaser Radish!",
        update_new_bot_radish_content: "Một bot mới, Teaser Radish, đã gia nhập hệ sinh thái. Bot nói tiếng Pháp này được xây dựng bằng Oceanic.js và được thiết kế để có độ ổn định tối đa.",
        update_new_bot_cpu_title: "CPU Teaser đã xuất hiện!",
        update_new_bot_cpu_content: "'Triết gia kỹ thuật số' CPU Teaser hiện đã online. Được xây dựng bằng Python và Disnake, sẵn sàng chia sẻ những suy ngẫm của mình.",
        update_new_bot_kite_title: "Nhìn kìa, trên bầu trời! Đó là Teaser Kite!",
        update_new_bot_kite_content: "Một... thực thể... mới đã xuất hiện trong Teaserverse. Mục đích của nó cũng rõ ràng như ngôn ngữ của nó: Kite!!",
        update_search_feature_title: "Cải tiến Thanh Tìm kiếm",
        update_search_feature_content: "Đã thêm nút Tìm, bôi nổi kết quả trên thẻ và modal, và nút xóa (✖) cạnh tiêu đề kết quả để thao tác nhanh hơn.",
        dev_modal_title: "Về nhà phát triển", dev_modal_content: "Một dev khá lười, thành thạo Python, Node.js và đang học Java. Thích lập trình nhiều bot với ngôn ngữ đa dạng.",
        chart_bot_singular: "bot", chart_bot_plural: "bot",
        timeline_link: "Timeline",
        settings_title: "Cài đặt", language_settings_title: "Cài đặt Ngôn ngữ", theme_settings_title: "Cài đặt Giao diện",
        role_iminibot: 'Cung cấp một hệ sinh thái giải trí toàn diện bao gồm: kinh tế, minigames, nghề nghiệp, và profile cá nhân hóa. Chỉ sử dụng lệnh prefix.', history_iminibot: 'Khởi đầu từ nền tảng no-code Botghost, sau đó được viết lại hoàn toàn bằng Python. "IminiBot (test)" là phiên bản staging cho đến v3.2 trước khi bị khai tử. Giai đoạn "Đại cập nhật" (v3.3 - v3.8) chứng kiến sự phát triển thần tốc, đôi khi có hai bản cập nhật trong một ngày.', roadmap_iminibot: 'Hướng đến "Huge Update 4.0: The Changed of The Era".',
        role_ramteaser: 'Teaser bot đầu tiên. Theo dõi nội dung từ 2 kênh YouTube và liên tục thay đổi trạng thái.', history_ramteaser: 'Ra đời từ thất bại trong việc host IminiBot, nó là "cụ tổ" đã khơi mào cho Teaserverse. Ban đầu dùng Nextcord, thử nghiệm với JDA (thất bại) và cuối cùng ổn định với discord.js.', funFact_ramteaser: 'Là teaser có uptime cao nhất Teaserverse. Chừng nào Bot-hosting còn hoạt động, uptime của "cụ" sẽ còn tăng mãi.',
        role_teaserlite: 'Giám sát và cập nhật chỉ số của server mỗi 5 phút.', history_teaserlite: 'Tên ban đầu là "Teaser Bun" (dùng Bun.js). Do vấn đề từ host, dự án đã bị "overwrite" và viết lại hoàn toàn bằng discord.py.', funFact_teaserlite: 'Cấu hình sẽ không bao giờ thay đổi do những hạn chế khắc nghiệt của host Zluqe.',
        role_teaserpotato: 'Thay đổi trạng thái ngẫu nhiên và cung cấp một vài lệnh slash cơ bản.', history_teaserpotato: 'Ra đời từ gói tài nguyên miễn phí của host Lunes. Sử dụng thư viện Eris siêu nhẹ để tối ưu cho cấu hình cực kỳ hạn chế. Từng bị Discord rate-limit do restart debug quá nhiều.', funFact_teaserpotato: 'Nếu may mắn, có thể được nâng cấp lên thành "Teaser Potato Ultimate" trong hơn 4 giờ, với cấu hình đủ sức "đè bẹp cả Teaserverse". Điều này sẽ không bao giờ xảy ra.',
        role_teaserhardcore: 'Cung cấp 5 lệnh slash độc lạ, sống đúng với tên gọi khi chạy thư viện Discord4J khó nhằn.', history_teaserhardcore: 'Một thử nghiệm về khả năng chịu đựng của nhà phát triển với một thư viện phức tạp. Bị rò rỉ RAM từ từ.', funFact_teaserhardcore: 'Sẽ không được cập nhật do độ phức tạp của thư viện. Host Karlo cung cấp RAM gấp 3 lần cho bot Java, đó là lý do Hardcore tồn tại.',
        role_teaserdust: 'Gửi heartbeat và duy trì kết nối với Discord API mà không cần thư viện, chỉ dùng raw WebSocket.', history_teaserdust: 'Ra đời từ ý tưởng "thay vì than phiền về 50MB RAM, tại sao không tối ưu nó hết mức có thể?". Toàn bộ bot chứa trong một file duy nhất.', funFact_teaserdust: 'Sống như một hạt bụi, không cần ai quan tâm.',
        role_playercycle: 'Đóng vai trò là "sử gia" của Teaserverse, cung cấp thông tin về tất cả các bot, kể cả những bot đã "tử trận".', history_playercycle: 'Thường xuyên ngoại tuyến do nhà phát triển quên gia hạn host hàng ngày. Đang "nghiên cứu" nguồn gốc bí mật của Teaserverse.', funFact_playercycle: 'Tính năng slideshow đổi avatar được thêm vào nhưng không được quan tâm đến việc nó có hoạt động hay không.',
        role_teasermusic: 'Bot phát nhạc sử dụng phiên bản tùy chỉnh của JMusicBot (JDA).', history_teasermusic: 'Lịch sử phát triển "quay như chong chóng". Sau nhiều thất bại khi tự code do quên cài ffmpeg, dự án đã chuyển sang nền tảng JMusicBot.', funFact_teasermusic: 'Dev đã dành khoảng 15 tiếng trong 3 đợt để sửa Lavalink trước khi nhận ra thiếu ffmpeg.',
        role_teaserdrift: 'Quản lý hệ thống Giveaway nâng cao với nhiều tính năng.', history_teaserdrift: 'Thừa hưởng tính năng Giveaway vốn được dự định cho Teaser Ultra. Xuất hiện một cách ngẫu nhiên với tư cách "dân giàu" trong hệ sinh thái.', funFact_teaserdrift: 'Sẽ được cập nhật các tính năng Quality of Life.',
        role_teaserai: 'Tích hợp Gemini API để cung cấp các tính năng AI. Hỗ trợ cả Prefix và Slash commands.', history_teaserai: 'Ban đầu được phát triển bằng C# (Discord.Net). Do hạn chế hỗ trợ từ host, dự án đã được tái cấu trúc sang Node.js để "đổi sự ngầu lấy hiệu suất".', funFact_teaserai: 'Được kỳ vọng sẽ trở thành Teaser bot mạnh mẽ nhất (trừ IminiBot).',
        role_teaserultra: 'Dự án tham vọng nhất, được định hướng sẽ có rất nhiều tính năng phức tạp.', history_teaserultra: 'Bị trì hoãn 4 lần do sự ra đời của các Teaser bot khác. Hiện tại chỉ có lệnh /ping và /mood.', funFact_teaserultra: 'Cả 4 lần trì hoãn đều do dev mải mê tạo các Teaser bot khác.',
        role_teaserradish: 'Một bot nói tiếng Pháp. Vai trò của nó là ổn định và yêu cầu cập nhật tối thiểu.', history_teaserradish: 'Được lên kế hoạch cho host KataBump (một host của Pháp), sử dụng thư viện Oceanic.js. Mọi thứ về nó đều bằng tiếng Pháp, từ console log đến comment trong code.', funFact_teaserradish: 'Đây là bot Teaser đầu tiên có README.md được viết đúng cách.',
        role_cputeaser: 'Một "triết gia kỹ thuật số" cung cấp các suy ngẫm và trích dẫn triết học.', history_cputeaser: 'Đang được host tạm ở Orihost sau trải nghiệm tồi tệ với EchoHost, nơi quảng cáo sai về tài nguyên CPU.', funFact_cputeaser: 'Dev đã bị lừa bởi lời hứa "80vCores CPU" của EchoHost, nhưng thực tế chỉ là 80% của một core.',
        role_teasereclipse: 'Một bot dự kiến sẽ theo dõi trạng thái người chơi và nói tiếng Nga.', history_teasereclipse: 'Một dự án được lên kế hoạch cho host WispByte để theo dõi hoạt động của người chơi.',
        role_teaserrebun: 'Một bot dự kiến cung cấp các kênh thoại tạm thời (TempVoice).', history_teaserrebun: 'Sự trả thù của Teaser Bun. Dự kiến sẽ tái sinh bằng công nghệ Bun hiện đại trên SillyDev.',
        role_teaserkite: 'Kite!!', history_teaserkite: 'Kite!!', funFact_teaserkite: 'Kite!!',
        role_teaserscnx: 'SCNX', history_teaserscnx: 'SCNX', funFact_teaserscnx: 'Đây là một "trò đùa" nội bộ của Teaserverse.',
        
        // Search-related translations
        search_placeholder: 'Tìm kiếm bot...',
        search_no_results: 'Không tìm thấy kết quả',
        search_no_results_desc: 'Không có bot nào phù hợp với "{term}"',
        search_results: 'Kết quả tìm kiếm cho',
        search_result: 'kết quả',
        search_results_plural: 'kết quả',
    },
    ja: {
		main_title: "Teaserverseエコシステム", main_subtitle: "ボットプロジェクト、その技術、そしてその背後にある物語のインタラクティブな分析。",
		tab_overview: "概要", tab_updates: "更新",
		ram_chart_title: "RAM割り当て (MB)", lang_chart_title: "言語分布",
		directory_title: "ボットディレクトリ", filter_all: "すべて", filter_stable: "安定", filter_dev: "開発中", filter_planned: "計画中", filter_joke: "冗談",
		view_details: "詳細を見る", modal_role: "役割と機能", modal_history: "歴史と背景", modal_fun_fact: "豆知識", modal_roadmap: "ロードマップ", modal_tech_specs: "技術仕様", modal_status: "状態", modal_host: "ホスト", modal_db: "データベース",
		card_ram: "RAM", card_cpu: "CPU", card_disk: "ディスク",
		update_type_bot_update: "ボット更新", update_type_new_feature: "新機能", update_type_new_bot: "新しいボット",
		update_iminibot_391_title: "IminiBot v3.9.1 - 安定性パッチ",
		update_iminibot_391_content: "データベース接続の問題に対処し、プロファイルコマンドのパフォーマンスを向上させるためにIminiBotのパッチをリリースしました。",
		update_repo_readme_title: "透明性イニシアチブ：リポジトリとREADMEが追加されました",
		update_repo_readme_content: "いくつかのボットの公開リポジトリと詳細なREADME.mdがリリースされました。IminiBotのREADME.mdも更新されました。",
		update_new_bot_radish_title: "Teaser Radishへようこそ！",
		update_new_bot_radish_content: "新しいボット、Teaser Radishがエコシステムに参加しました。このフランス語を話すボットはOceanic.jsで構築されており、最大限の安定性のために設計されています。",
		update_new_bot_cpu_title: "CPU Teaserが登場！",
		update_new_bot_cpu_content: "「デジタル哲学者」CPU Teaserがオンラインになりました。PythonとDisnakeで構築され、その考えを共有する準備ができています。",
		update_new_bot_kite_title: "空を見て！Teaser Kiteだ！",
		update_new_bot_kite_content: "新しい…存在…がTeaserverseに現れました。その目的は、その言語と同じくらい明確です：Kite!!",
		update_search_feature_title: "検索バーの改善",
		update_search_feature_content: "明示的な検索ボタン、カードとモーダル内の結果のハイライト、検索結果の横にクリア（✖）アクションを追加しました。",
		dev_modal_title: "開発者について", dev_modal_content: "少し怠け者な開発者で、Python、Node.jsに堪能で、現在Javaを学習中です。様々な言語で多様なボットをプログラミングすることを楽しんでいます。",
		chart_bot_singular: "ボット", chart_bot_plural: "ボット",
		timeline_link: "タイムライン",
		settings_title: "設定", language_settings_title: "言語設定", theme_settings_title: "テーマ設定",
		role_iminibot: '経済、ミニゲーム、職業、プロファイルカスタマイズなど、包括的なエンターテイメントエコシステムを提供します。プレフィックスコマンドのみを使用します。', history_iminibot: 'ノーコードプラットフォームBotghostから始まり、その後Pythonで完全に書き直されました。「IminiBot (test)」はv3.2までのステージングバージョンでしたが、その後廃止されました。「グレートアップデート」フェーズ（v3.3 - v3.8）では急速な開発が見られ、時には1日に2回のアップデートがありました。', roadmap_iminibot: '「Huge Update 4.0: The Changed of The Era」に向かっています。',
		role_ramteaser: '最初のTeaserボット。2つのYouTubeチャンネルのコンテンツを監視し、継続的にステータスを変更します。', history_ramteaser: 'IminiBotのホスティングの失敗から生まれ、Teaserverseの火付け役となった「祖先」です。当初はNextcordを使用し、JDAを試しましたが（失敗）、最終的にdiscord.jsで安定しました。', funFact_ramteaser: 'Teaserverseで最も高い稼働率を誇ります。Bot-hostingが稼働している限り、その稼働時間は増え続けます。',
		role_teaserlite: '5分ごとにサーバーの統計を監視および更新します。', history_teaserlite: '元々の名前は「Teaser Bun」（Bun.jsを使用）。ホストの問題により、プロジェクトは「上書き」され、discord.pyで完全に書き直されました。', funFact_teaserlite: 'ホストZluqeの厳しい制限により、その構成は決して変更されません。',
		role_teaserpotato: 'ランダムにステータスを変更し、いくつかの基本的なスラッシュコマンドを提供します。', history_teaserpotato: 'Lunesホストの無料リソースから生まれました。超軽量のErisライブラリを使用して、非常に限られたスペックに最適化しています。デバッグ中の再起動が多すぎて、かつてDiscordによってレート制限を受けました。', funFact_teaserpotato: '運が良ければ、「Teaser Potato Ultimate」に4時間以上アップグレードでき、Teaserverse全体を「粉砕」するのに十分なパワーを持つことができます。これは決して起こりません。',
		role_teaserhardcore: '5つのニッチなスラッシュコマンドを提供し、難しいDiscord4Jライブラリを実行することでその名に恥じない存在です。', history_teaserhardcore: '複雑なライブラリに対する開発者の忍耐力を試す実験。ゆっくりとしたメモリリークに悩まされています。', funFact_teaserhardcore: 'ライブラリの複雑さのため、更新されません。ホストのKarloはJavaボットに3倍のRAMを提供しており、それがHardcoreが存在する理由です。',
		role_teaserdust: 'ハートビートを送信し、ライブラリなしで、生のWebSocketのみを使用してDiscord APIとの接続を維持します。', history_teaserdust: '50MBのRAMについて不平を言う代わりに、可能な限り最適化しようという考えから生まれました。ボット全体が単一ファイルに収められています。', funFact_teaserdust: '誰も気にかけない、塵のように生きています。',
		role_playercycle: 'Teaserverseの「歴史家」として機能し、倒れたものを含むすべてのボットに関する情報を提供します。', history_playercycle: '開発者が毎日ホストを更新するのを忘れるため、頻繁にオフラインになります。現在、Teaserverseの秘密の起源を「調査中」です。', funFact_playercycle: 'アバターのスライドショー機能が追加されましたが、実際に機能するかどうかは誰も気にしていません。',
		role_teasermusic: 'JMusicBot（JDA）の改造版を使用した音楽ボット。', history_teasermusic: '「こま」のような開発史。ffmpegのインストールを忘れたためにゼロからコーディングする試みが何度も失敗した後、プロジェクトはJMusicBotプラットフォームに切り替えました。', funFact_teasermusic: '開発者は、ffmpegが欠けていることに気づく前に、Lavalinkを修正しようと3回のセッションで約15時間を費やしました。',
		role_teaserdrift: '多くの機能を備えた高度なプレゼント企画システムを管理します。', history_teaserdrift: '元々Teaser Ultra向けに意図されていたプレゼント企画機能を継承しました。エコシステムに「金持ちの子供」としてランダムに現れました。', funFact_teaserdrift: '生活の質の機能で更新されます。',
		role_teaserai: 'Gemini APIを統合してAI機能を提供します。プレフィックスコマンドとスラッシュコマンドの両方をサポートします。', history_teaserai: '当初はC#（Discord.Net）で開発されました。ホストのサポートが限られていたため、プロジェクトはリファクタリングされNode.jsに移行されました。', funFact_teaserai: '（IminiBotを除いて）最も強力なTeaserボットになると期待されています。',
		role_teaserultra: '最も野心的なプロジェクトで、多くの複雑な機能を備えることを目的としています。', history_teaserultra: '他のTeaserボットの作成により4回遅延しました。現在、/pingと/moodコマンドしかありません。', funFact_teaserultra: '4回の遅延はすべて、開発者が代わりに他のTeaserボットを作成することに気を取られたことが原因でした。',
		role_teaserradish: 'フランス語を話すボット。その役割は安定しており、最小限の更新を必要とすることです。', history_teaserradish: 'KataBumpホスト（フランスのホスト）向けに計画され、Oceanic.jsライブラリを使用しています。コンソールログからコードコメントまで、すべてがフランス語です。', funFact_teaserradish: 'これは、適切に書かれたREADME.mdを持つ最初のTeaserボットです。',
		role_cputeaser: '思考や哲学的な引用を提供する「デジタル哲学者」。', history_cputeaser: 'CPUリソースを偽って宣伝したEchoHostでの悪い経験の後、一時的にOrihostでホストされています。', funFact_cputeaser: '開発者はEchoHostの「80vCores CPU」の約束にだまされましたが、実際には単一コアの80％にすぎませんでした。',
		role_teasereclipse: 'プレイヤーのステータスを監視し、ロシア語を話す予定のボット。', history_teasereclipse: 'プレイヤーの活動を監視するためにWispByteホストで計画されているプロジェクト。',
		role_teaserrebun: '一時的な音声チャンネル（TempVoice）を提供する予定のボット。', history_teaserrebun: 'Teaser Bunの復讐。SillyDevで最新のBunテクノロジーを使用して生まれ変わる予定です。',
		role_teaserkite: 'Kite!!', history_teaserkite: 'Kite!!', funFact_teaserkite: 'Kite!!',
		role_teaserscnx: 'SCNX', history_teaserscnx: 'SCNX', funFact_teaserscnx: 'これはTeaserverseの内部ジョークです。',
		// Search-related translations
		search_placeholder: 'ボットを検索...',
		search_no_results: '結果が見つかりません',
		search_no_results_desc: '"{term}" に一致するボットは見つかりませんでした',
		search_results: '検索結果',
		search_result: '件',
		search_results_plural: '件',
	},
	fr: {
		main_title: "Écosystème Teaserverse", main_subtitle: "Une analyse interactive des projets de bots, de leurs technologies et des histoires qui les sous-tendent.",
		tab_overview: "Aperçu", tab_updates: "Mises à jour",
		ram_chart_title: "Allocation de RAM (Mo)", lang_chart_title: "Distribution des langages",
		directory_title: "Annuaire des bots", filter_all: "Tout", filter_stable: "Stable", filter_dev: "En développement", filter_planned: "Planifié", filter_joke: "Blague",
		view_details: "Voir les détails", modal_role: "Rôle et fonctionnalité", modal_history: "Histoire et contexte", modal_fun_fact: "Fait amusant", modal_roadmap: "Feuille de route", modal_tech_specs: "Spécifications techniques", modal_status: "Statut", modal_host: "Hôte", modal_db: "Base de données",
		card_ram: "RAM", card_cpu: "CPU", card_disk: "Disque",
		update_type_bot_update: "Mise à jour du bot", update_type_new_feature: "Nouvelle fonctionnalité", update_type_new_bot: "Nouveau bot",
		update_iminibot_391_title: "IminiBot v3.9.1 - Patch de stabilité",
		update_iminibot_391_content: "Publication d'un patch pour IminiBot afin de résoudre les problèmes de connexion à la base de données et d'améliorer les performances de la commande de profil.",
		update_repo_readme_title: "Initiative de transparence : Ajout de dépôts et de README",
		update_repo_readme_content: "Des dépôts publics et des fichiers README.md détaillés ont été publiés pour plusieurs bots. Le README.md d'IminiBot a également été mis à jour.",
		update_new_bot_radish_title: "Bienvenue à Teaser Radish !",
		update_new_bot_radish_content: "Un nouveau bot, Teaser Radish, a rejoint l'écosystème. Ce bot francophone est construit avec Oceanic.js et est conçu pour une stabilité maximale.",
		update_new_bot_cpu_title: "CPU Teaser est arrivé !",
		update_new_bot_cpu_content: "Le 'philosophe numérique' CPU Teaser est maintenant en ligne. Construit avec Python et Disnake, il est prêt à partager ses pensées.",
		update_new_bot_kite_title: "Regardez, dans le ciel ! C'est Teaser Kite !",
		update_new_bot_kite_content: "Une nouvelle... entité... est apparue dans le Teaserverse. Son but est aussi clair que son langage : Kite !!",
		update_search_feature_title: "Améliorations de la barre de recherche",
		update_search_feature_content: "Ajout d'un bouton de recherche explicite, mise en évidence des résultats sur les cartes et modales, et une action de suppression (✖) à côté des résultats pour une exploration plus rapide.",
		dev_modal_title: "À propos du développeur", dev_modal_content: "Un développeur un peu paresseux, compétent en Python, Node.js et apprenant actuellement Java. Aime programmer une gamme variée de bots avec différents langages.",
		chart_bot_singular: "bot", chart_bot_plural: "bots",
		timeline_link: "Chronologie",
		settings_title: "Paramètres", language_settings_title: "Paramètres de langue", theme_settings_title: "Paramètres du thème",
		role_iminibot: 'Fournit un écosystème de divertissement complet incluant l\'économie, des mini-jeux, des métiers et une personnalisation de profil approfondie. Il utilise exclusivement des commandes à préfixe.', history_iminibot: 'A commencé sur la plateforme sans code Botghost, puis entièrement réécrit en Python. "IminiBot (test)" était une version de développement jusqu\'à la v3.2 avant d\'être retirée. La phase de "Grande mise à jour" (v3.3 - v3.8) a vu un développement rapide, parfois avec deux mises à jour en une seule journée.', roadmap_iminibot: 'Se dirige vers la "Huge Update 4.0: The Changed of The Era".',
		role_ramteaser: 'Le premier bot Teaser. Surveille le contenu de 2 chaînes YouTube et change continuellement de statut.', history_ramteaser: 'Né d\'un échec d\'hébergement d\'IminiBot, il a été l\' "ancêtre" qui a déclenché le Teaserverse. A initialement utilisé Nextcord, a expérimenté avec JDA (échec), et s\'est finalement stabilisé avec discord.js.', funFact_ramteaser: 'A le plus long temps de fonctionnement dans le Teaserverse. Tant que Bot-hosting est en vie, son temps de fonctionnement continuera d\'augmenter.',
		role_teaserlite: 'Surveille et met à jour les statistiques du serveur toutes les 5 minutes.', history_teaserlite: 'Initialement nommé "Teaser Bun" (utilisant Bun.js). En raison de problèmes avec l\'hôte, le projet a été "écrasé" et entièrement réécrit en discord.py.', funFact_teaserlite: 'Sa configuration ne changera jamais en raison des limitations sévères de son hôte, Zluqe.',
		role_teaserpotato: 'Change de statut aléatoirement et fournit quelques commandes slash de base.', history_teaserpotato: 'Né des ressources gratuites de l\'hôte Lunes. Utilise la bibliothèque ultra-légère Eris pour optimiser les spécifications extrêmement limitées. A été une fois limité en débit par Discord en raison de redémarrages excessifs pendant le débogage.', funFact_teaserpotato: 'S\'il a de la chance, il pourrait être mis à niveau en "Teaser Potato Ultimate" pendant plus de 4 heures avec des spécifications suffisamment puissantes pour "écraser tout le Teaserverse". Cela n\'arrivera jamais.',
		role_teaserhardcore: 'Fournit 5 commandes slash de niche, faisant honneur à son nom en exécutant la difficile bibliothèque Discord4J.', history_teaserhardcore: 'Une expérience sur l\'endurance du développeur face à une bibliothèque complexe. Il souffre d\'une lente fuite de mémoire.', funFact_teaserhardcore: 'Ne sera pas mis à jour en raison de la complexité de la bibliothèque. L\'hôte, Karlo, fournit 3 fois plus de RAM pour les bots Java, ce qui explique l\'existence de Hardcore.',
		role_teaserdust: 'Envoie des pulsations et maintient une connexion avec l\'API Discord sans aucune bibliothèque, en utilisant uniquement des WebSockets bruts.', history_teaserdust: 'Né de l\'idée "au lieu de se plaindre de 50 Mo de RAM, pourquoi ne pas l\'optimiser autant que possible ?". Le bot entier est contenu dans un seul fichier.', funFact_teaserdust: 'Vit comme une poussière, sans avoir besoin d\'attention.',
		role_playercycle: 'Acts as the "historian" of Teaserverse, providing information about all bots, including the fallen ones.', history_playercycle: 'Frequently offline because the developer forgets to renew the host daily. It is currently "researching" the secret origin of Teaserverse.', funFact_playercycle: 'The avatar slideshow feature was added but no one cares if it actually works.',
		role_teasermusic: 'Music bot using a modified version of JMusicBot (JDA).', history_teasermusic: 'A "spinning top" development history. After many failed attempts at coding it from scratch due to forgetting to install ffmpeg, the project switched to the JMusicBot platform.', funFact_teasermusic: 'The developer spent about 15 hours over 3 sessions trying to fix Lavalink before realizing ffmpeg was missing.',
		role_teaserdrift: 'Manages an advanced Giveaway system with many features.', history_teaserdrift: 'Inherited the Giveaway feature originally intended for Teaser Ultra. Appeared randomly as a "rich kid" in the ecosystem.', funFact_teaserdrift: 'Will be updated with Quality of Life features.',
		role_teaserai: 'Integrates the Gemini API to provide AI features. Supports both Prefix and Slash commands.', history_teaserai: 'Initially developed in C# (Discord.Net). Due to limited host support, the project was refactored to Node.js to "trade coolness for performance".', funFact_teaserai: 'Expected to become the most powerful Teaser bot (besides IminiBot).',
		role_teaserultra: 'The most ambitious project, intended to have many complex features.', history_teaserultra: 'Delayed 4 times due to the creation of other Teaser bots. Currently only has /ping and /mood commands.', funFact_teaserultra: 'All 4 delays were caused by the developer getting distracted and creating other Teaser bots instead.',
		role_teaserradish: 'A French-speaking bot. Its role is to be stable and require minimal updates.', history_teaserradish: 'Planned for the KataBump host (a French host), using the Oceanic.js library. Everything about it is in French, from console logs to code comments.', funFact_teaserradish: 'This is the first Teaser bot with a properly written README.md.',
		role_cputeaser: 'A "digital philosopher" that provides thoughts and philosophical quotes.', history_cputeaser: 'Hosted temporarily on Orihost after a bad experience with EchoHost, which falsely advertised its CPU resources.', funFact_cputeaser: 'The developer was tricked by EchoHost\'s "80vCores CPU" promise, which turned out to be only 80% of a single core.',
		role_teasereclipse: 'A planned bot that will monitor player status and speak Russian.', history_teasereclipse: 'A project planned for the WispByte host to monitor player activity.',
		role_teaserrebun: 'A planned bot to provide temporary voice channels (TempVoice).', history_teaserrebun: 'The revenge of Teaser Bun. Planned to be reborn using modern Bun technology on SillyDev.',
		role_teaserkite: 'Kite!!', history_teaserkite: 'Kite!!', funFact_teaserkite: 'Kite!!',
		role_teaserscnx: 'SCNX', history_teaserscnx: 'SCNX', funFact_teaserscnx: 'This is an internal joke in Teaserverse.',
		// Search-related translations
		search_placeholder: 'Rechercher des bots...',
		search_no_results: 'Aucun résultat',
		search_no_results_desc: 'Aucun bot ne correspond à "{term}"',
		search_results: 'Résultats de recherche',
		search_result: 'résultat',
		search_results_plural: 'résultats',
	},
	es: {
		main_title: "Ecosistema Teaserverse", main_subtitle: "Un análisis interactivo de los proyectos de bots, sus tecnologías y las historias detrás de ellos.",
		tab_overview: "Resumen", tab_updates: "Actualizaciones",
		ram_chart_title: "Asignación de RAM (MB)", lang_chart_title: "Distribución de lenguajes",
		directory_title: "Directorio de bots", filter_all: "Todos", filter_stable: "Estable", filter_dev: "En desarrollo", filter_planned: "Planificado", filter_joke: "Broma",
		view_details: "Ver detalles", modal_role: "Rol y funcionalidad", modal_history: "Historia y contexto", modal_fun_fact: "Dato curioso", modal_roadmap: "Hoja de ruta", modal_tech_specs: "Especificaciones técnicas", modal_status: "Estado", modal_host: "Host", modal_db: "Base de datos",
		card_ram: "RAM", card_cpu: "CPU", card_disk: "Disco",
		update_type_bot_update: "Actualización de Bot", update_type_new_feature: "Nueva Característica", update_type_new_bot: "Nuevo Bot",
		update_iminibot_391_title: "IminiBot v3.9.1 - Parche de estabilidad",
		update_iminibot_391_content: "Se lanzó un parche para IminiBot para solucionar problemas de conexión de la base de datos y mejorar el rendimiento del comando de perfil.",
		update_repo_readme_title: "Iniciativa de Transparencia: Repositorios y READMEs Añadidos",
		update_repo_readme_content: "Se han publicado repositorios públicos y archivos README.md detallados para varios bots. El README.md de IminiBot también ha sido actualizado.",
		update_new_bot_radish_title: "¡Bienvenido Teaser Radish!",
		update_new_bot_radish_content: "Un nuevo bot, Teaser Radish, se ha unido al ecosistema. Este bot de habla francesa está construido con Oceanic.js y está diseñado para una máxima estabilidad.",
		update_new_bot_cpu_title: "¡Ha llegado CPU Teaser!",
		update_new_bot_cpu_content: "El 'filósofo digital' CPU Teaser ya está en línea. Construido con Python y Disnake, está listo para compartir sus pensamientos.",
		update_new_bot_kite_title: "¡Mira, en el cielo! ¡Es Teaser Kite!",
		update_new_bot_kite_content: "Una nueva... entidad... ha aparecido en el Teaserverse. Su propósito es tan claro como su idioma: ¡¡Kite!!",
		update_search_feature_title: "Mejoras en la barra de búsqueda",
		update_search_feature_content: "Se añadió un botón de búsqueda explícito, resaltado de resultados en tarjetas y modales, y una acción de borrar (✖) junto a los resultados para una exploración más rápida.",
		dev_modal_title: "Sobre el desarrollador", dev_modal_content: "Un desarrollador un tanto perezoso, competente en Python, Node.js y actualmente aprendiendo Java. Disfruta programando una amplia gama de bots con varios lenguajes.",
		chart_bot_singular: "bot", chart_bot_plural: "bots",
		timeline_link: "Línea de tiempo",
		settings_title: "Configuración", language_settings_title: "Configuración de Idioma", theme_settings_title: "Configuración de Tema",
		role_iminibot: 'Proporciona un ecosistema de entretenimiento completo que incluye economía, minijuegos, trabajos y personalización profunda del perfil. Utiliza exclusivamente comandos de prefijo.', history_iminibot: 'Comenzó en la plataforma sin código Botghost, luego fue reescrito completamente en Python. "IminiBot (test)" fue una versión de prueba hasta la v3.2 antes de ser retirada. La fase de "Gran Actualización" (v3.3 - v3.8) vio un desarrollo rápido, a veces con dos actualizaciones en un día.', roadmap_iminibot: 'Se dirige hacia la "Huge Update 4.0: The Changed of The Era".',
		role_ramteaser: 'El primer bot Teaser. Monitorea el contenido de 2 canales de YouTube y cambia continuamente su estado.', history_ramteaser: 'Nacido de un fracaso al alojar IminiBot, fue el "ancestro" que encendió el Teaserverse. Inicialmente usó Nextcord, experimentó con JDA (falló) y finalmente se estabilizó con discord.js.', funFact_ramteaser: 'Tiene el mayor tiempo de actividad en Teaserverse. Mientras Bot-hosting esté vivo, su tiempo de actividad seguirá aumentando.',
		role_teaserlite: 'Monitorea y actualiza las estadísticas del servidor cada 5 minutos.', history_teaserlite: 'Originalmente llamado "Teaser Bun" (usando Bun.js). Debido a problemas con el host, el proyecto fue "sobrescrito" y completamente reescrito en discord.py.', funFact_teaserlite: 'Su configuración nunca cambiará debido a las severas limitaciones de su host, Zluqe.',
		role_teaserpotato: 'Cambia de estado aleatoriamente y proporciona algunos comandos de barra básicos.', history_teaserpotato: 'Nacido de los recursos gratuitos del host Lunes. Utiliza la biblioteca ultraligera Eris para optimizar para especificaciones extremadamente limitadas. Una vez fue limitado por Discord debido a reinicios excesivos durante la depuración.', funFact_teaserpotato: 'Si tiene suerte, podría actualizarse a "Teaser Potato Ultimate" durante más de 4 horas con especificaciones lo suficientemente potentes como para "aplastar todo el Teaserverse". Esto nunca sucederá.',
		role_teaserhardcore: 'Proporciona 5 comandos de barra de nicho, haciendo honor a su nombre al ejecutar la difícil biblioteca Discord4J.', history_teaserhardcore: 'Un experimento en la resistencia del desarrollador contra una biblioteca compleja. Sufre de una lenta fuga de memoria.', funFact_teaserhardcore: 'No se actualizará debido a la complejidad de la biblioteca. El host, Karlo, proporciona 3 veces más RAM para los bots de Java, que es como existe Hardcore.',
		role_teaserdust: 'Envoie des pulsations et maintient une connexion avec l\'API Discord sans aucune bibliothèque, en utilisant uniquement des WebSockets bruts.', history_teaserdust: 'Né de l\'idée "au lieu de se plaindre de 50 Mo de RAM, pourquoi ne pas l\'optimiser autant que possible ?". Le bot entier est contenu dans un seul fichier.', funFact_teaserdust: 'Vit comme une poussière, sans avoir besoin d\'attention.',
		role_playercycle: 'Actúa como el "historiador" del Teaserverse, proporcionando información sobre todos los bots, incluidos los caídos.', history_playercycle: 'A menudo está desconectado porque el desarrollador olvida renovar el host diariamente. Actualmente está "investigando" el origen secreto del Teaserverse.', funFact_playercycle: 'Se añadió la función de presentación de avatares, pero a nadie le importa si realmente funciona.',
		role_teasermusic: 'Music bot using a modified version of JMusicBot (JDA).', history_teasermusic: 'A "spinning top" development history. After many failed attempts at coding it from scratch due to forgetting to install ffmpeg, the project switched to the JMusicBot platform.', funFact_teasermusic: 'The developer spent about 15 hours over 3 sessions trying to fix Lavalink before realizing ffmpeg was missing.',
		role_teaserdrift: 'Manages an advanced Giveaway system with many features.', history_teaserdrift: 'Inherited the Giveaway feature originally intended for Teaser Ultra. Appeared randomly as a "rich kid" in the ecosystem.', funFact_teaserdrift: 'Will be updated with Quality of Life features.',
		role_teaserai: 'Integrates the Gemini API to provide AI features. Supports both Prefix and Slash commands.', history_teaserai: 'Initially developed in C# (Discord.Net). Due to limited host support, the project was refactored to Node.js to "trade coolness for performance".', funFact_teaserai: 'Expected to become the most powerful Teaser bot (besides IminiBot).',
		role_teaserultra: 'The most ambitious project, intended to have many complex features.', history_teaserultra: 'Delayed 4 times due to the creation of other Teaser bots. Currently only has /ping and /mood commands.', funFact_teaserultra: 'All 4 delays were caused by the developer getting distracted and creating other Teaser bots instead.',
		role_teaserradish: 'A French-speaking bot. Its role is to be stable and require minimal updates.', history_teaserradish: 'Planned for the KataBump host (a French host), using the Oceanic.js library. Everything about it is in French, from console logs to code comments.', funFact_teaserradish: 'This is the first Teaser bot with a properly written README.md.',
		role_cputeaser: 'A "digital philosopher" that provides thoughts and philosophical quotes.', history_cputeaser: 'Hosted temporarily on Orihost after a bad experience with EchoHost, which falsely advertised its CPU resources.', funFact_cputeaser: 'The developer was tricked by EchoHost\'s "80vCores CPU" promise, which turned out to be only 80% of a single core.',
		role_teasereclipse: 'A planned bot that will monitor player status and speak Russian.', history_teasereclipse: 'A project planned for the WispByte host to monitor player activity.',
		role_teaserrebun: 'A planned bot to provide temporary voice channels (TempVoice).', history_teaserrebun: 'The revenge of Teaser Bun. Planned to be reborn using modern Bun technology on SillyDev.',
		role_teaserkite: 'Kite!!', history_teaserkite: 'Kite!!', funFact_teaserkite: 'Kite!!',
		role_teaserscnx: 'SCNX', history_teaserscnx: 'SCNX', funFact_teaserscnx: 'This is an internal joke in Teaserverse.',
		// Search-related translations
		search_placeholder: 'Buscar bots...',
		search_no_results: 'No se encontraron resultados',
		search_no_results_desc: 'No se encontró ningún bot que coincida con "{term}"',
		search_results: 'Resultados de búsqueda',
		search_result: 'resultado',
		search_results_plural: 'resultados',
	},
	ru: {
		main_title: "Экосистема Teaserverse", main_subtitle: "Интерактивный анализ бот-проектов, их технологий и историй, стоящих за ними.",
		tab_overview: "Обзор", tab_updates: "Обновления",
		ram_chart_title: "Распределение ОЗУ (МБ)", lang_chart_title: "Распределение языков",
		directory_title: "Каталог ботов", filter_all: "Все", filter_stable: "Стабильный", filter_dev: "В разработке", filter_planned: "Запланировано", filter_joke: "Шутка",
		view_details: "Посмотреть детали", modal_role: "Роль и функциональность", modal_history: "История и контекст", modal_fun_fact: "Интересный факт", modal_roadmap: "Дорожная карта", modal_tech_specs: "Технические характеристики", modal_status: "Статус", modal_host: "Хост", modal_db: "База данных",
		card_ram: "ОЗУ", card_cpu: "ЦП", card_disk: "Диск",
		update_type_bot_update: "Обновление бота", update_type_new_feature: "Новая функция", update_type_new_bot: "Новый бот",
		update_iminibot_391_title: "IminiBot v3.9.1 - Патч стабильности",
		update_iminibot_391_content: "Выпущен патч для IminiBot для устранения проблем с подключением к базе данных и повышения производительности команды профиля.",
		update_repo_readme_title: "Инициатива прозрачности: добавлены репозитории и README",
		update_repo_readme_content: "Опубликованы общедоступные репозитории и подробные файлы README.md для нескольких ботов. README.md IminiBot также был обновлен.",
		update_new_bot_radish_title: "Добро пожаловать, Teaser Radish!",
		update_new_bot_radish_content: "Новый бот, Teaser Radish, присоединился к экосистеме. Этот франкоговорящий бот создан на Oceanic.js и разработан для максимальной стабильности.",
		update_new_bot_cpu_title: "CPU Teaser прибыл!",
		update_new_bot_cpu_content: "'Цифровой философ' CPU Teaser теперь в сети. Созданный на Python и Disnake, он готов поделиться своими мыслями.",
		update_new_bot_kite_title: "Смотрите, в небе! Это Teaser Kite!",
		update_new_bot_kite_content: "Новая... сущность... появилась в Teaserverse. Ее цель так же ясна, как и ее язык: Kite!!",
		update_search_feature_title: "Улучшения панели поиска",
		update_search_feature_content: "Добавлена явная кнопка поиска, выделение результатов на карточках и модальных окнах, а также действие очистки (✖) рядом с результатами поиска для более быстрого исследования.",
		dev_modal_title: "О разработчике", dev_modal_content: "Несколько ленивый разработчик, владеющий Python, Node.js и в настоящее время изучающий Java. Любит программировать разнообразных ботов на разных языках.",
		chart_bot_singular: "бот", chart_bot_plural: "ботов",
		timeline_link: "Хронология",
		settings_title: "Настройки", language_settings_title: "Настройки языка", theme_settings_title: "Настройки темы",
		role_iminibot: 'Предоставляет комплексную развлекательную экосистему, включающую экономику, мини-игры, задания и глубокую настройку профиля. Использует исключительно префиксные команды.', history_iminibot: 'Началось с платформы без кода Botghost, затем полностью переписано на Python. "IminiBot (test)" был средой для стейджинга до v3.2, после чего был выведен из эксплуатации. Фаза "Большого обновления" (v3.3 - v3.8) ознаменовалась быстрым развитием, иногда с двумя обновлениями в один день.', roadmap_iminibot: 'Движется к "Huge Update 4.0: The Changed of The Era".',
		role_ramteaser: 'Первый бот Teaser. Мониторит контент с 2 YouTube-каналов и постоянно меняет свой статус.', history_ramteaser: 'Родился из-за невозможности разместить IminiBot, он был "предком", который зажег Teaserverse. Изначально использовал Nextcord, экспериментировал с JDA (неудачно) и, наконец, стабилизировался с discord.js.', funFact_ramteaser: 'Имеет самое высокое время безотказной работы в Teaserverse. Пока Bot-hosting жив, его время безотказной работы будет продолжать расти.',
		role_teaserlite: 'Мониторит и обновляет статистику сервера каждые 5 минут.', history_teaserlite: 'Изначально назывался "Teaser Bun" (использовал Bun.js). Из-за проблем с хостом проект был "перезаписан" и полностью переписан на discord.py.', funFact_teaserlite: 'Его конфигурация никогда не изменится из-за жестких ограничений его хоста, Zluqe.',
		role_teaserpotato: 'Случайно меняет статус и предоставляет несколько базовых слеш-команд.', history_teaserpotato: 'Родился из бесплатных ресурсов хоста Lunes. Использует сверхлегкую библиотеку Eris для оптимизации под крайне ограниченные характеристики. Однажды был ограничен Discord по скорости запросов из-за чрезмерных перезапусков во время отладки.', funFact_teaserpotato: 'Если повезет, его можно будет обновить до "Teaser Potato Ultimate" более чем на 4 часа с характеристиками, достаточно мощными, чтобы "сокрушить весь Teaserverse". Этого никогда не произойдет.',
		role_teaserhardcore: 'Предоставляет 5 команд слеш-ниш, оправдывая свое название работой со сложной библиотекой Discord4J.', history_teaserhardcore: 'Эксперимент на выносливость разработчика против сложной библиотеки. Страдает от медленной утечки памяти.', funFact_teaserhardcore: 'Не будет обновляться из-за сложности библиотеки. Хост, Karlo, предоставляет в 3 раза больше ОЗУ для ботов на Java, благодаря чему и существует Hardcore.',
		role_teaserdust: 'Отправляет сердцебиения и поддерживает соединение с Discord API без какой-либо библиотеки, используя только необработанные WebSockets.', history_teaserdust: 'Родился из идеи "вместо того, чтобы жаловаться на 50 МБ ОЗУ, почему бы не оптимизировать ее максимально?". Весь бот содержится в одном файле.', funFact_teaserdust: 'Живет как пылинка, не требуя внимания.',
		role_playercycle: 'Actúa como el "historiador" del Teaserverse, proporcionando información sobre todos los bots, incluidos los caídos.', history_playercycle: 'A menudo está desconectado porque el desarrollador olvida renovar el host diariamente. Actualmente está "investigando" el origen secreto del Teaserverse.', funFact_playercycle: 'Se añadió la función de presentación de avatares, pero a nadie le importa si realmente funciona.',
		role_teasermusic: 'Music bot using a modified version of JMusicBot (JDA).', history_teasermusic: 'A "spinning top" development history. After many failed attempts at coding it from scratch due to forgetting to install ffmpeg, the project switched to the JMusicBot platform.', funFact_teasermusic: 'The developer spent about 15 hours over 3 sessions trying to fix Lavalink before realizing ffmpeg was missing.',
		role_teaserdrift: 'Manages an advanced Giveaway system with many features.', history_teaserdrift: 'Inherited the Giveaway feature originally intended for Teaser Ultra. Appeared randomly as a "rich kid" in the ecosystem.', funFact_teaserdrift: 'Will be updated with Quality of Life features.',
		role_teaserai: 'Integrates the Gemini API to provide AI features. Supports both Prefix and Slash commands.', history_teaserai: 'Initially developed in C# (Discord.Net). Due to limited host support, the project was refactored to Node.js to "trade coolness for performance".', funFact_teaserai: 'Expected to become the most powerful Teaser bot (besides IminiBot).',
		role_teaserultra: 'The most ambitious project, intended to have many complex features.', history_teaserultra: 'Delayed 4 times due to the creation of other Teaser bots. Currently only has /ping and /mood commands.', funFact_teaserultra: 'All 4 delays were caused by the developer getting distracted and creating other Teaser bots instead.',
		role_teaserradish: 'A French-speaking bot. Its role is to be stable and require minimal updates.', history_teaserradish: 'Planned for the KataBump host (a French host), using the Oceanic.js library. Everything about it is in French, from console logs to code comments.', funFact_teaserradish: 'This is the first Teaser bot with a properly written README.md.',
		role_cputeaser: 'A "digital philosopher" that provides thoughts and philosophical quotes.', history_cputeaser: 'Hosted temporarily on Orihost after a bad experience with EchoHost, which falsely advertised its CPU resources.', funFact_cputeaser: 'The developer was tricked by EchoHost\'s "80vCores CPU" promise, which turned out to be only 80% of a single core.',
		role_teasereclipse: 'A planned bot that will monitor player status and speak Russian.', history_teasereclipse: 'A project planned for the WispByte host to monitor player activity.',
		role_teaserrebun: 'A planned bot to provide temporary voice channels (TempVoice).', history_teaserrebun: 'The revenge of Teaser Bun. Planned to be reborn using modern Bun technology on SillyDev.',
		role_teaserkite: 'Kite!!', history_teaserkite: 'Kite!!', funFact_teaserkite: 'Kite!!',
		role_teaserscnx: 'SCNX', history_teaserscnx: 'SCNX', funFact_teaserscnx: 'This is an internal joke in Teaserverse.',
		// Search-related translations
		search_placeholder: 'Поиск ботов...',
		search_no_results: 'Результатов не найдено',
		search_no_results_desc: 'Не найдено ботов, соответствующих "{term}"',
		search_results: 'Результаты поиска',
		search_result: 'результат',
		search_results_plural: 'результатов',
	},
};